export const NAVIGATION_STATES: Record<number, string> = {
  0: 'motoring',
  1: 'anchored',
  2: 'not under command',
  3: 'restricted manouverability',
  4: 'constrained by draft',
  5: 'moored',
  6: 'aground',
  7: 'fishing',
  8: 'sailing',
  9: 'hazardous material high speed',
  10: 'IMO hazard',
  11: 'power-driven vessel towing astern',
  12: 'power-driven vessel pushing ahead or towing alongside',
  13: 'reserved for future use',
  14: 'ais-sart',
  15: 'default',
};

export const VESSEL_TYPES: Record<number, string> = {
  20: 'Wing In Ground',
  29: 'Wing In Ground (no other information)',
  30: 'Fishing',
  31: 'Towing',
  32: 'Towing exceeds 200m or wider than 25m',
  33: 'Engaged in dredging or underwater operations',
  34: 'Engaged in diving operations',
  35: 'Engaged in military operations',
  36: 'Sailing',
  37: 'Pleasure',
  40: 'High speed craft',
  41: 'High speed craft carrying dangerous goods',
  42: 'High speed craft hazard cat B',
  43: 'High speed craft hazard cat C',
  44: 'High speed craft hazard cat D',
  49: 'High speed craft (no additional information)',
  50: 'Pilot vessel',
  51: 'SAR',
  52: 'Tug',
  53: 'Port tender',
  54: 'Anti-pollution',
  55: 'Law enforcement',
  56: 'Spare',
  57: 'Spare #2',
  58: 'Medical',
  59: 'RR Resolution No.1',
  60: 'Passenger ship',
  69: 'Passenger ship (no additional information)',
  70: 'Cargo ship',
  71: 'Cargo ship carrying dangerous goods',
  72: 'Cargo ship hazard cat B',
  73: 'Cargo ship hazard cat C',
  74: 'Cargo ship hazard cat D',
  79: 'Cargo ship (no additional information)',
  80: 'Tanker',
  81: 'Tanker carrying dangerous goods',
  82: 'Tanker hazard cat B',
  83: 'Tanker hazard cat C',
  84: 'Tanker hazard cat D',
  89: 'Tanker (no additional information)',
  90: 'Other',
  91: 'Other carrying dangerous goods',
  92: 'Other hazard cat B',
  93: 'Other hazard cat C',
  94: 'Other hazard cat D',
  99: 'Other (no additional information)',
};

export const POSITION_TYPES: Record<number, string> = {
  1: 'GPS',
  2: 'GLONASS',
  3: 'combined GPS/GLONASS',
  4: 'Loran-C',
  5: 'Chayka',
  6: 'integrated navigation system',
  7: 'surveyed',
  8: 'Galileo',
  9: 'not used',
  10: 'not used',
  11: 'not used',
  12: 'not used',
  13: 'not used',
  14: 'not used',
  15: 'internal GNSS',
};
